version: '3.9'

services:
  web:
    build: .
    container_name: ditutto_web
    ports:
      - "8082:80"
    volumes:
      - ./frontend:/var/www/html
      - ./backend/api:/var/www/html/backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Para conexión desde PHP (por si querés usarlos en el código)
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: DiTutto
      DB_USER: utu
      DB_PASSWORD: 12345678

  db:
    image: postgres:15
    container_name: ditutto_db
    restart: always
    environment:
      POSTGRES_DB: DiTutto
      POSTGRES_USER: utu
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utu -d DiTutto"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ditutto_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data_new:
